# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congregation', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('weekend', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('presentation_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True, null=True)),
                ('meeting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingItem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.CongregationMember')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('week_day', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('congregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregation.Congregation')),
            ],
        ),
        migrations.AddField(
            model_name='meetingpart',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingType'),
        ),
        migrations.AddField(
            model_name='meetingitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingPart'),
        ),
    ]
