# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congregation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('reading', models.BooleanField(default=False)),
                ('demo', models.BooleanField(default=False)),
                ('discourse', models.BooleanField(default=False)),
                ('book_page', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('presentation_date', models.DateField(auto_now=True)),
                ('lesson_passed', models.BooleanField(default=False)),
                ('lesson_comments', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_modification', models.DateTimeField(auto_now_add=True, null=True)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Background')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.CongregationMember')),
            ],
        ),
    ]
