# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_load_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooltask',
            options={'permissions': (('can_view_all_tasks', 'Can see all available tasks'),
                                     ('can_judge_tasks', 'Can judge presented tasks by popele'))},
        ),
    ]
