# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0004_auto_20161103_0929'),
        ('school', '0003_set_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltask',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_person', to='congregation.CongregationMember'),
        ),
        migrations.AddField(
            model_name='schooltask',
            name='replacement',
            field=models.BooleanField(default=False),
        ),
    ]
