# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0004_auto_20160204_1130'),
        ('school', '0003_auto_20160111_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltask',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slave_person', to='congregation.CongregationMember'),
        ),
        migrations.AddField(
            model_name='schooltask',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_person', to='congregation.CongregationMember'),
        ),
    ]
