# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0009_auto_20160205_1246'),
        ('school', '0004_auto_20160204_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_person', to='congregation.CongregationMember'),
        ),
    ]
