# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_schooltask_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltask',
            name='lesson_passed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
