# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20160209_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltask',
            name='lesson_passed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
