# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('system_account', models.BooleanField(default=False)),
                ('perms', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male', max_length=1)),
                ('last_modification', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
