# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:08
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command
from django.contrib.auth.models import User


def load_fixtures(state_apps, schema_editor):
    call_command('loaddata', 'users_django', 'users_profile')


def set_default_users_password():
    for user in User.objects.all():
        user.set_password(user.username)
        user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
        migrations.RunPython(set_default_users_password)
    ]