# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:08
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.models import User
from django.apps import apps


def load_fixtures(state_apps, schema_editor):
    call_command('loaddata', 'users_django', 'congregation_privilages', 'congregations', 'congregations_members_pie_ka', 'users_profile', 'congregation_member_privilages')


def set_default_users_password(state_apps, schema_editor):
    for user in User.objects.all():
        user.set_password(user.username)
        user.save()


def create_superuser(state_apps, schema_editor):
    User = apps.get_model(app_label='auth', model_name='User')
    user = User.objects.create_superuser('root', 'a@a.pl', 'prodigy666')
    user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
        migrations.RunPython(create_superuser),
        migrations.RunPython(set_default_users_password),
    ]