# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-30 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male', max_length=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_modification',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 30, 15, 22, 25, 350698)),
        ),
    ]
