# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-30 14:04
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps


def create_superuser(state_apps, schema_editor):
    User = apps.get_model(app_label='auth', model_name='User')
    user = User.objects.create_superuser('root', 'a@a.pl', 'prodigy666')
    user.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_load_data'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
