# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregationmember',
            options={'ordering': ['user'], 'permissions': (('can_manage', 'Can see all available tasks'),)},
        ),
    ]
