# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0003_auto_20160126_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congregationmember',
            options={'ordering': ['user'], 'permissions': (('can_manage', 'Can manage'),)},
        ),
    ]
