# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0004_auto_20160204_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongregationMemberPrivilages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregation.CongregationMember')),
            ],
        ),
        migrations.CreateModel(
            name='CongregationPrivilages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='all', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='congregationmemberprivilages',
            name='privilage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congregation.CongregationPrivilages'),
        ),
    ]
