# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0006_congregationprivilages_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CongregationMemberPrivilages',
            new_name='CongregationMemberPrivileges',
        ),
        migrations.RenameModel(
            old_name='CongregationPrivilages',
            new_name='CongregationPrivileges',
        ),
    ]
