# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0007_auto_20160204_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congregationmemberprivileges',
            old_name='privilage',
            new_name='privilege',
        ),
    ]
