# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0008_auto_20160205_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregationmember',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='elder',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='lector',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='master',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='pioneer',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='reader_only',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='school_allow',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='servant',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='slave',
        ),
        migrations.RemoveField(
            model_name='congregationmember',
            name='sound_sysop',
        ),
    ]
